# Generated by Django 4.0.2 on 2022-02-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('members_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Siteuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('iin', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField(default=0)),
                ('to_user_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('file', models.FileField(blank=True, upload_to='upload')),
                ('status', models.IntegerField(default=0)),
                ('sms', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='test', max_length=300)),
                ('members_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.siteuser')),
            ],
        ),
    ]
